### ISSUE TITLE
Question about install.sh

### ISSUE THREAD

**Issue by rudSarkar** [Huntinex/rauton#1]
Hi,

How did you install https://github.com/Huntinex/rauton/blob/main/install.sh#L2-L8 these packages with apt? or are there any source lists which provide users to install the go package using apt?

**Comment by Huntinex** [comment]
i was in the kali linux

for installing go packages you can use `go install` or `go get`
but if you using kali linux you can install some go packages that exists on
kali sources

**Comment by Huntinex** [comment]
i was in the kali linux

for installing go packages you can use `go install` or `go get`
but if you using kali linux you can install some go packages that exists on kali sources

**Comment by rudSarkar** [comment]
> 

Did you see the link I shared you used apt on your installation file?  Check the link https://github.com/Huntinex/rauton/blob/main/install.sh#L2-L8

**Comment by Huntinex** [comment]
yes i see the link
i used apt to install because i was in the kali linux

**Comment by rudSarkar** [comment]
Is it the default source list? Because I used kali as well

**Comment by Huntinex** [comment]
may be

But I edited `install.sh` . I hope your problem is solved !

**Comment by rudSarkar** [comment]
Yeah looks good let you know about it

**Comment by Huntinex** [comment]
in [#8efa5ce](https://github.com/Huntinex/rauton/commit/8efa5ceac4fdde7290133f849e1edf6ca618daee) i solved this problem

**Comment by rudSarkar** [comment]
> in [#8efa5ce](https://github.com/Huntinex/rauton/commit/8efa5ceac4fdde7290133f849e1edf6ca618daee) i solved this problem

I saw that already
